package com.mitchmele.messageconsumer.algorithmconsumer.mongodb

import com.mitchmele.messageconsumer.algorithmconsumer.algorithm_store.AlgorithmDomainModel
import org.springframework.data.mongodb.repository.MongoRepository

interface AlgorithmMongoRepository : MongoRepository<AlgorithmDomainModel, String>